name: Run integration tests
description: Deploy infrastructure, test it, and destroy it
inputs:
  aws_role_arn:
    description: AWS IAM Role to use
    required: true
  boundary_policy:
    description: IAM managed policy to apply as permissions boundary
    required: true
  env_suffix:
    description: 'Environment suffix'
    required: true
  google_project:
    description: Google Project ID for testing
    required: true
  google_service_account:
    description: Google service account for federated authentication
    required: true
  google_workload_identity_provider:
    description: Google identity provider for federated authentication
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-to-assume: ${{ inputs.aws_role_arn }}
        role-session-name: IhlpGitHubActions

    # https://github.com/google-github-actions/auth#configuring-gcloud
    - id: 'gcpauth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.8.1'
      with:
        workload_identity_provider: ${{ inputs.google_workload_identity_provider }}
        service_account: ${{ inputs.google_service_account }}
    - name: 'Set up GCP Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0.6.0'

    - run: echo "Installing node modules"
      shell: bash
    - name: Install modules
      run: npm ci
      shell: bash
    - run: echo "Running tests"
      shell: bash
    - name: Run integration tests
      run: ENV_SUFFIX=${{ inputs.env_suffix }} AWS_PERMISSIONS_BOUNDARY_ARN=${{ inputs.boundary_policy }} npm run integration
      shell: bash
