name: Lint and Unit Test

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    name: Lint & unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Check formatting
        run: npm run format
      - name: Run unit tests
        # TODO: switch to coverage when 80% threshold met
        # run: npm run coverage
        run: npm run test
